name: COMMON DOCKER IMAGE BUILDER

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: debweassemble
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: debweassemble/spm-devtools:latest


      # - name: Setup Docker on macOS
      #   id: setup-docker
      #   uses: douglascamata/setup-docker-macos-action@v1.0.1
      #   with:
      #     lima: v1.2.1
      #     colima: v0.9.1
      #     colima-network-address: false
      # - name: docker login
      #   run: docker login -u debweassemble -p ${{ secrets.DOCKER_HUB_TOKEN }}
      # - name: Build the Docker image
      #   run: DOCKER_BUILDKIT=0 docker build . --file Dockerfile --tag debweassemble/spm-devtools:latest
      # - name: publish docker image to hub
      #   run: docker push debweassemble/spm-devtools:latest
